### ISSUE TITLE
Cannot read property 'seo' of null

### ISSUE THREAD

**Issue by rohanrajpal** [sharu725/hagura-sveltekit#1]
Cloned -> ran `pnpm i` -> `pnpm run dev`

Got this error
```
❯ pnpm run dev                                                                                                                                              (base) 13:20:25

> hagura-svelte@0.0.1 dev /home/rohan/Documents/github/hagura-sveltekit
> svelte-kit dev


  SvelteKit v1.0.0-next.122

  local:   http://localhost:3000
  network: not exposed
  network: not exposed

  Use --host to expose server to other devices on this network


1:20:48 PM [vite] new dependencies found: svelte-paginate, updating...
1:20:48 PM [vite] ✨ dependencies updated, reloading page...
Cannot read property 'seo' of null
TypeError: Cannot read property 'seo' of null
    at eval (/home/rohan/Documents/github/hagura-sveltekit/src/routes/index.svelte:29:61)
    at Object.$$render (/home/rohan/Documents/github/hagura-sveltekit/node_modules/.pnpm/svelte@3.38.3/node_modules/svelte/internal/index.js:1555:22)
    at Object.default (//home/rohan/Documents/github/hagura-sveltekit/.svelte-kit/dev/generated/root.svelte:57:127)
    at eval (/home/rohan/Documents/github/hagura-sveltekit/src/routes/__layout.svelte:16:87)
    at Object.$$render (/home/rohan/Documents/github/hagura-sveltekit/node_modules/.pnpm/svelte@3.38.3/node_modules/svelte/internal/index.js:1555:22)
    at eval (//home/rohan/Documents/github/hagura-sveltekit/.svelte-kit/dev/generated/root.svelte:55:122)
    at $$render (/home/rohan/Documents/github/hagura-sveltekit/node_modules/.pnpm/svelte@3.38.3/node_modules/svelte/internal/index.js:1555:22)
    at Object.render (/home/rohan/Documents/github/hagura-sveltekit/node_modules/.pnpm/svelte@3.38.3/node_modules/svelte/internal/index.js:1563:26)
    at render_response (file:///home/rohan/Documents/github/hagura-sveltekit/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.122_svelte@3.38.3/node_modules/@sveltejs/kit/dist/ssr.js:377:28)
    at async respond$1 (file:///home/rohan/Documents/github/hagura-sveltekit/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.122_svelte@3.38.3/node_modules/@sveltejs/kit/dist/ssr.js:1153:10)

```

did i miss anything?

**Comment by rohanrajpal** [comment]
Okay everything worked after running `pnpm run dev` for the second time
